logging:
  level:
    com.abhishekvermaa10: INFO
    org.springframework.web: WARN
  file:
    name: logs/Petistaan-test.log
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
spring:
  application:
    name: Petistaan-test
  datasource:
    password: ${MYSQL_PASSWORD}
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  profiles:
    active: test
server:
  port: 0  # Random port for tests
  servlet:
    context-path: /petistaan
springdoc:
  api-docs:
    path: /apiDocumentation
  swagger-ui:
    path: /swagger.html
management:
  endpoints:
    web:
      exposure:
        include: health
info:
  app:
    name: Petistaan (Test)
    message: Test environment
    profile: test

