spring:
  profiles:
    active: dev

logging:
  file:
    name: logs/Petistaan-dev.log
    path: logs
  level:
    com.abhishekvermaa10: DEBUG
    org.springframework.web: DEBUG
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.path}/${spring.application.name}-%d{yyyy-MM-dd}-%i.log
      max-file-size: 10MB
spring:
  application:
    name: Petistaan-dev
  datasource:
    password: ${MYSQL_PASSWORD:}
    url: jdbc:mysql://localhost:3306/petistaan
    username: ${MYSQL_USERNAME:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never
server:
  port: 8080
  servlet:
    context-path: /petistaan
springdoc:
  api-docs:
    path: /apiDocumentation
  swagger-ui:
    path: /swagger.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Petistaan (Dev)
    message: Development environment
    profile: dev

# Dummy transliterate API configuration for dev profile
transliteration:
  api:
    url: dummy
    enabled: false

